#!/bin/bash

folderPath="diplomacyOnline"
sourceFolder="src"
commitFolder="commitFiles"

echo "commit files"

cd ~/${folderPath}/${commitFolder}
rm -f *

for fileKind in css html js gas
do
    cd ~/${folderPath}/${sourceFolder}/${fileKind}
    for file in $(ls)
    do
        originalFile=~/${folderPath}/${sourceFolder}/${fileKind}/${file}
        case ${fileKind} in
            css )
                newFile=~/${folderPath}/${commitFolder}/${fileKind}_${file/.css/.html}
                ;;
            js )
                newFile=~/${folderPath}/${commitFolder}/${fileKind}_${file/.js/.html}
                ;;
            *)
                newFile=~/${folderPath}/${commitFolder}/${fileKind}_${file}
                ;;
        esac

        cp -f ${originalFile} ${newFile}

        case ${fileKind} in
            css )
                echo -e "\n</script>" >> ${newFile}
                sed -i -e "1i <script>" ${newFile}
                ;;
            js )
                echo -e "\n</style>" >> ${newFile}
                sed -i -e "1i <style>" ${newFile}
                ;;
        esac
    done
done

cd ~/${folderPath}
#gapps upload

git add .
git commit -m "\"$1\""
git push
